### ISSUE TITLE
Can we only calculate the mesh input?

### ISSUE THREAD

**Issue by chenhbo** [gzhang8/DenseMapPosterior.jl#1]
Thanks for your nice work!

For the custom dataset, we only have the output mesh .ply file.
Can we use this work to evaluate it?

Thx

**Comment by gzhang8** [comment]
@chenhbo The short answer is no. 

For this metric to work. It need both the 3D model file together with estimated camera trajectory and original images (for this implementation, RGB-D data are required).

Can you explain how you get the mesh without the original image sequence?

**Comment by chenhbo** [comment]
Thank you so much for for your reply.

Our original input is the 3D point cloud. Our target is reconstruct the mesh from point cloud.

Thank you.

**Comment by gzhang8** [comment]
> Thank you so much for for your reply.
> 
> Our original input is the 3D point cloud. Our target is reconstruct the mesh from point cloud.
> 
> Thank you.

I see. For this, I would suggest using CloudCompare to check point to mesh distance

**Comment by chenhbo** [comment]
Thank you for your suggestion.
